version: "3.1"
services:
  simple-weather-react:
    build:
      context: .
    image: simple-weather-react:1
    container_name: simple-weather-react 
    restart: always
    ports:
      - 80:80
      - 443:443
